const GET_REPORT_LOADING = 'GET_REPORT_LOADING';
const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
const GET_REPORT_FAILURE = 'GET_REPORT_FAILURE';
const GET_GRAPH_DATA = 'GET_GRAPH_DATA';

export { GET_REPORT_LOADING, GET_REPORT_SUCCESS, GET_REPORT_FAILURE, GET_GRAPH_DATA };